### PR TITLE
Test iCloud

### LINKED ISSUE #149: Integrate iCloud into testsuite
Although calendar sync seemed to work fine, there have been some problems with contacts synchronization to iCloud. They're all fixed, but testing against iCloud still would be nice.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6952829-integrate-icloud-into-testsuite?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F574345&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #565: Problem with syncing and handling a non-color value as color metadata for a calendar
This is linked to https://github.com/pimutils/khal/issues/596.

## Description:
When setting up a new iCloud hosted calendar with vdirsyncer, I had the experience of it syncing down a metadata file for the calendar's color with the string contents of "`None`". I have since not been able to reproduce this behavior, but based on the debug log (posted below), this value still seems to exist server-side at least. The syncing of this value caused a crash in `ikhal` (see issue mentioned at beginning of this post) due to not being able to parse the value of "`None`" from the color metadata file. 

Steps (this is as precise as I can recall):
1. This calendar was created in [Fantastical 2 on OS X](http://flexibits.com/fantastical), and was assigned a color when it was created. 
2. I closed Fantastical and then went to modify the configuration file for `vdirsyncer` for it to discover and start syncing this calendar. The initial `vdirsyncer discover` and `vdirsyncer sync` worked successfully.
3. At this point I was able to view the calendar in `ikhal` without issue but it lacked a color.
4. I created the file `color` locally in this calendar's directory to give it color metadata and gave it a **different** custom color.
5. After this point I ran `vdirsyncer metasync` and was still able to view it in `ikhal`.
6. I then deleted the color metadata file and ran `vdirsyncer metasync` again, to ensure that there was a different color being used on the server-side.
7. I got back a file with the contents of "None", which I didn't notice until I ran `ikhal` and it crashed when trying to parse this string.
8. I was able to replace the value in the file with my custom color again and `ikhal` correctly opens the file.

Additional Notes:
* All of these pieces of software use different storage locations for the calendar data for this specific calendar. The only consistent thing here is what is on the server.
    * Calendar.app (Apple software) seems to correctly show the custom color I picked for the cloud.
    * Fantastical 2 doesn't show any color for this specific calendar.
    * ikhal shows the **different** custom color I have selected
* In the attached log below the calendar in question has had the color metadata file remove from the filesystem prior to running in an attempt to reproduce getting `vdirsyncer` to download this bit of metadata. I am not seeing it get re-created, but based on the server response it is definitely there.
* Note that there are two different colors involved in the syncing here, I have different colors for displaying in my terminal vs on my mobile phone's calendar app. The cloud stores the color of the calendar that my phone should have, and i have a local override of the color in my `khal` config.

## Version Info

**vdirsyncer** version:
`vdirsyncer, version 0.14.1`

Server Software:
`Apple iCloud`

Python Version:
`Python 3.6.0`

Operating System:
```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

Config file:
```
[general]
status_path = "~/.config/vdirsyncer/status"

[pair icloud]
a = "local_icloud"
b = "remote_icloud"
collections = ["from a", "from b"]
conflict_resolution = "a wins"
metadata = ["color", "displayname"]

[storage local_icloud]
type = "filesystem"
path = "~/Calendars/icloud"
fileext = ".ics"

[storage remote_icloud]
type = "caldav"
url = "https://caldav.icloud.com/"
username.fetch = ["command", "/usr/local/bin/secure-env", "get", "--key:vdirsyncer-icloud-username"]
password.fetch = ["command", "/usr/local/bin/secure-env", "get", "--key:vdirsyncer-icloud-password"]
verify_fingerprint = "F5:CC:B1:A7:24:13:36:07:54:8B:00:D8:EB:40:2E:FC:A3:07:6D:58"

```

Debug Log for `vdirsyncer --verbosity DEBUG metasync`:
```
Metasyncing icloud/XXX
debug: PROPFIND https://p31-caldav.icloud.com:443/***/calendars/XXX/
debug: {
    'User-Agent': 'vdirsyncer', 
    'Content-Type': 'application/xml; charset=UTF-8', 
    'Depth': '0'
}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <ns0:calendar-color xmlns:ns0="http://apple.com/ns/ical/" />
debug:                 </D:prop>
debug:             </D:propfind>
debug:         
debug: Sending request...
debug: 207
debug: {
    'Server': 'AppleHttpServer/3b804a0', 
    'Date': 'Sat, 25 Feb 2017 18:07:03 GMT', 
    'Content-Type': 'text/xml', 
    'Content-Length': '390', 
    'Connection': 'keep-alive', 
    'Last-Modified': 'Sat, 25 Feb 2017 21:35:07 GMT', 
    'DAV': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-audit, calendar-managed-attachments, calendarserver-sharing, calendarserver-subscribed, calendarserver-home-sync', 
    'Accept-Ranges': 'bytes', 
    'X-Responding-Server': '***', 
    'X-Transaction-Id': '***', 
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 
    'via': '***', 
    'X-Apple-Request-UUID': '***', 
    'access-control-expose-headers': 'X-Apple-Request-UUID, Via'
}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/***/calendars/XXX/</href>
debug:     <propstat>
debug:       <prop>
debug:         <calendar-color symbolic-color='custom' xmlns='http://apple.com/ns/ical/'>None</calendar-color>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: Key: color
debug: A: 
debug: B: None
debug: S: None
Copying color to remote_icloud/XXX
debug: PROPPATCH https://p31-caldav.icloud.com:443/***/calendars/XXX/
debug: {
    'User-Agent': 'vdirsyncer', 
    'Content-Type': 'application/xml; charset=UTF-8'
}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propertyupdate xmlns:D="DAV:">
debug:                 <D:set>
debug:                     <D:prop>
debug:                         <ns0:calendar-color xmlns:ns0="http://apple.com/ns/ical/" />
debug:                     </D:prop>
debug:                 </D:set>
debug:             </D:propertyupdate>
debug:         
debug: Sending request...
debug: 207
debug: {
    'Server': 'AppleHttpServer/3b804a0', 
    'Date': 'Sat, 25 Feb 2017 18:07:03 GMT', 
    'Content-Type': 'text/xml', 
    'Content-Length': '423', 
    'Connection': 'keep-alive', 
    'Last-Modified': 'Sat, 25 Feb 2017 21:35:07 GMT', 
    'DAV': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-audit, calendar-managed-attachments, calendarserver-sharing, calendarserver-subscribed, calendarserver-home-sync', 
    'Accept-Ranges': 'bytes', 
    'X-Responding-Server': '***', 
    'X-Transaction-Id': '***', 
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 
    'via': '***', 
    'X-Apple-Request-UUID': '***', 
    'access-control-expose-headers': 'X-Apple-Request-UUID, Via'
}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/***/calendars/XXX/</href>
debug:     <propstat>
debug:       <prop>
debug:         <calendar-color symbolic-color='custom' xmlns='http://apple.com/ns/ical/'/>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:       <responsedescription>OK</responsedescription>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: PROPFIND https://p31-caldav.icloud.com:443/***/calendars/XXX/
debug: {
    'User-Agent': 'vdirsyncer', 
    'Content-Type': 'application/xml; charset=UTF-8', 
    'Depth': '0'
}
debug: <?xml version="1.0" encoding="utf-8" ?>
debug:             <D:propfind xmlns:D="DAV:">
debug:                 <D:prop>
debug:                     <ns0:displayname xmlns:ns0="DAV:" />
debug:                 </D:prop>
debug:             </D:propfind>
debug:         
debug: Sending request...
debug: 207
debug: {
    'Server': 'AppleHttpServer/3b804a0', 
    'Date': 'Sat, 25 Feb 2017 18:07:03 GMT', 
    'Content-Type': 'text/xml', 
    'Content-Length': '333', 
    'Connection': 'keep-alive', 
    'Last-Modified': 'Sun, 26 Feb 2017 02:07:03 GMT', 
    'DAV': '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-audit, calendar-managed-attachments, calendarserver-sharing, calendarserver-subscribed, calendarserver-home-sync', 
    'Accept-Ranges': 'bytes',
     'X-Responding-Server': '***', 
    'X-Transaction-Id': '***', 
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
    'via': '***', 
    'X-Apple-Request-UUID': '***', 
    'access-control-expose-headers': 'X-Apple-Request-UUID, Via'
}
debug: <?xml version='1.0' encoding='UTF-8'?>
debug: <multistatus xmlns='DAV:'>
debug:   <response>
debug:     <href>/***/calendars/XXX/</href>
debug:     <propstat>
debug:       <prop>
debug:         <displayname>Work Events</displayname>
debug:       </prop>
debug:       <status>HTTP/1.1 200 OK</status>
debug:     </propstat>
debug:   </response>
debug: </multistatus>
debug: Key: displayname
debug: A: Work Events
debug: B: Work Events
debug: S: Work Events
```

### PR DESCRIPTION
**Pull request by untitaker**
Fix #149 
Fix #565

### CODE REVIEW

**Comment by hobarrera** [comment]
Nice 👍🏻🎉

**Comment by hobarrera** [comment]
I you can provide my with `ICLOUD_USERNAME` and `ICLOUD_PASSWORD`, I can try creating a VTODO inside a collection with my iPhone and we can see if there's any difference, if it appears to vdirsyncer, etc.

**Comment by untitaker** [comment]
We would need to know how collections are created (i.e. intercept traffic of iPhone). I know that *existing* task lists can be synchronized.

**Comment by hobarrera** [comment]
What's the best way to do this? Set up a local server, configure maximum logging, and provide the output query?

Radicale is the easiest, right?

**Comment by untitaker** [comment]
It's easier to use mitmproxy with the original iCloud server

**Comment by hobarrera** [comment]
Here's the request (that was fun and way easier than expected!):

Header:
```
Host:                   p34-caldav.icloud.com
X-Apple-Client-Info:    <iPhone7,2> <iPhone OS;10.2.1;14D27> <com.apple.coredav/1.0.1 (com.apple.dataaccess.dataaccessd/1.0)>
Accept:                 */*
Authorization:          X-MobileMe-AuthToken MTgxMzY3Njc1MzpBUUFBQUFCWVpyQU1reWFZWDVNUjFWcmI0amlTZlozdEZOK2Faa1U9
Content-Encoding:       gzip
Accept-Language:        en-gb
Cache-Control:          no-transform
Accept-Encoding:        gzip, deflate
X-Apple-DAV-Pushtoken:  261525c47f7996b02f4bd5582330920170c48f5b7479be2b298651aa6606fbe5
Content-Length:         550
User-Agent:             iOS/10.2.1 (14D27) dataaccessd/1.0
Connection:             keep-alive
Content-Type:           text/xml
```
(I didn't find how to export this from mitmproxy, so just copy-pasted it).

Body:
```
<?xml version="1.0" encoding="UTF-8"?>
<B:mkcalendar xmlns:B="urn:ietf:params:xml:ns:caldav">
  <A:set xmlns:A="DAV:">
    <A:prop>
      <A:displayname>Test999</A:displayname>
      <F:calendar-color xmlns:F="http://apple.com/ns/ical/">#cc73e1</F:calendar-color>
      <B:calendar-timezone>BEGIN:VCALENDAR&#13;
VERSION:2.0&#13;
CALSCALE:GREGORIAN&#13;
BEGIN:VTIMEZONE&#13;
TZID:America/Argentina/Buenos_Aires&#13;
BEGIN:DAYLIGHT&#13;
TZOFFSETFROM:-0300&#13;
DTSTART:20071230T000000&#13;
TZNAME:GMT-3&#13;
TZOFFSETTO:-0200&#13;
RDATE:20071230T000000&#13;
RDATE:20081019T000000&#13;
END:DAYLIGHT&#13;
BEGIN:STANDARD&#13;
TZOFFSETFROM:-0200&#13;
RRULE:FREQ=YEARLY;UNTIL=20090315T020000Z;BYMONTH=3;BYDAY=3SU&#13;
DTSTART:20080316T000000&#13;
TZNAME:GMT-3&#13;
TZOFFSETTO:-0300&#13;
END:STANDARD&#13;
END:VTIMEZONE&#13;
END:VCALENDAR&#13;
</B:calendar-timezone>
      <B:schedule-calendar-transp>
        <B:transparent/>
      </B:schedule-calendar-transp>
      <B:supported-calendar-component-set>
        <B:comp name="VTODO"/>
      </B:supported-calendar-component-set>
      <F:calendar-order xmlns:F="http://apple.com/ns/ical/">3</F:calendar-order>
    </A:prop>
  </A:set>
</B:mkcalendar>
```

[supported-calendar-component-set](https://tools.ietf.org/html/rfc4791#section-5.2.3) is the important bit. As expected after the above query, the new list did not appear on the calendar app, only on the reminders app.

**Comment by untitaker** [comment]
Continuing at #570

**Pull request merged**
