### PR TITLE
fix yaml syntax

### PR DESCRIPTION
**Pull request by stevepeak**
This will fix the status for sure. The comment may be fixed as well since the yaml is now valid

> CC https://github.com/codecov/support/issues/162#issuecomment-250472579

### CODE REVIEW

**Comment by untitaker** [comment]
Which filename is correct `.codecov.yml` or `codecov.yml`?

**Comment by untitaker** [comment]
Also thanks for the PR

**Comment by stevepeak** [comment]
Both path names will work. 👍

**Comment by untitaker** [comment]
Hmm, under https://codecov.io/gh/pimutils/vdirsyncer/settings/yaml I still see the default config @stevepeak

**Pull request merged**
