### PR TITLE
Add calendar-description to the meta data

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
When a CalDAV collection has calendar-description set and vdirsyncer synchronizes the “meta” data, synchronize also the calendar description.

### CODE REVIEW

**Comment by dilyanpalauzov** [comment]
Will this be integrated?

I want to use vdirsyncer to do one-way sync and get the full state of the server.  In fact I want also this change:
```diff
diff --git a/vdirsyncer/storage/dav.py b/vdirsyncer/storage/dav.py
--- a/vdirsyncer/storage/dav.py
+++ b/vdirsyncer/storage/dav.py
@@ -729,6 +729,7 @@ class CalDAVStorage(DAVStorage):
     _property_table.update({
         'color': ('calendar-color', 'http://apple.com/ns/ical/'),
         'description': ('calendar-description', 'urn:ietf:params:xml:ns:caldav'),
+        'calendar-order': ('calendar-order', 'http://apple.com/ns/ical/'),
     })
 
     def __init__(self, start_date=None, end_date=None,

```

**Comment by dilyanpalauzov** [comment]
I have updated the changeset to integrate carddav:addressbook-description and the `calendar-order` properties.  The latter is supported by NextClound and [Evolution](https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/297).

**Comment by WhyNotHugo** [comment]
Sorry, I just realised I wrote a review and never actually published it :(

I've merged `master` into this and updated the docs a bit. I'll go ahead and merge after all is green.

**Review by WhyNotHugo — APPROVED** [review]

**Comment by WhyNotHugo** [comment]
Thanks!

**Pull request merged**
