### PR TITLE
Add __main__.py to ease development.

### PR DESCRIPTION
**Pull request by lucc**
This makes it possible to execute vdirsyncer directly from the git repository
like this:

    cd path/to/repository/
    python setup.py build     # to generate version.py
    export PYTHONPATH=.       # to hide any installed versions of vdirsyncer
    python -m vdirsyncer

### CODE REVIEW

**Comment by lucc** [comment]
I just saw that one should install a dev version with `make install-dev` but that fails for me because it tries to install to the global `site-package` dir and I don't want the development version there.

Are there any disadvantages when running vdirsyncer directly from source like above (for development)?

**Comment by untitaker** [comment]
Click (the CLI framework we use) expects the program to be installed. I think the reason was that it can't reliably detect the program name otherwise.

On 7 April 2016 12:17:09 CEST, Lucas Hoffmann <notifications@github.com> wrote:
>I just saw that one should install a dev version with `make
>install-dev` but that fails for me because it tries to install to the
>global `site-package` dir and I don't want the development version
>there.
>
>Are there any disadvantages when running vdirsyncer directly from
>source like above (for development)?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/408#issuecomment-206798861

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lucc** [comment]
If I run `PYTHONPATH=. python -m vdirsyncer` it prints 
```
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...

  vdirsyncer -- synchronize calendars and contacts

Options:
  -v, --verbosity LVL  Either CRITICAL, ERROR, WARNING, INFO or DEBUG
  --version            Show the version and exit.
  --help               Show this message and exit.

Commands:
  discover  Refresh collection cache for the given pairs.
  metasync  Synchronize metadata of the given collections...
  repair    Repair a given collection.
  sync      Synchronize the given collections or pairs.
```
So it assumes the name is `__main__.py`.

Is there any other supported method which will allow me to run a development version without installing to the system wide package location or modifying and executing commands from the makefile manually.

**Comment by untitaker** [comment]
Yes you should use a virtualenv. IIRC the docs contain such info as well (on mobile, can't verify), if not, it probably should be added.

On 7 April 2016 16:13:13 CEST, Lucas Hoffmann <notifications@github.com> wrote:
>If I run `PYTHONPATH=. python -m vdirsyncer` it prints 
>```
>Usage: __main__.py [OPTIONS] COMMAND [ARGS]...
>
>  vdirsyncer -- synchronize calendars and contacts
>
>Options:
>  -v, --verbosity LVL  Either CRITICAL, ERROR, WARNING, INFO or DEBUG
>  --version            Show the version and exit.
>  --help               Show this message and exit.
>
>Commands:
>  discover  Refresh collection cache for the given pairs.
>  metasync  Synchronize metadata of the given collections...
>  repair    Repair a given collection.
>  sync      Synchronize the given collections or pairs.
>```
>So it assumes the name is `__main__.py`.
>
>Is there any other supported method which will allow me to run a
>development version without installing to the system wide package
>location or modifying and executing commands from the makefile
>manually.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/408#issuecomment-206925253

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marmarek** [comment]
You can use virtualenv.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by untitaker** [comment]
So I'd like to close this PR: Virtualenv is already linked in https://vdirsyncer.readthedocs.org/en/stable/contributing.html. I also think that the "Getting Started" guide of the official virtualenv docs is simple enough.

What would be neat is a `__main__` that aborts and tells the user to install vdirsyncer properly though :grin:

**Comment by lucc** [comment]
Maybe it is because I never had to use virtualenv before but my experience was not very smooth. Well I will learn something new now ...

I think the info how to install vdirsyncer does not belong in `__main__.py`.

**Comment by geier** [comment]
If you are using bash or zsh, use virtualenwrapper (use virtualfish for
fish). It's than as easy as `mkvirtualenv vdirsyncer` for creating a new
virtualenv named "vdirsyncer" (if you want to activate it later do
`workon vdirsyncer`) and than install vdirsyncer with `pip install -e .`
(from the git repo).


Quoting Lucas Hoffmann (2016-04-08 15:30:53)

**Pull request closed without merging**
