### PR TITLE
fully resolve well-known URI

### PR DESCRIPTION
**Pull request by posativ**
Currently, `find_dav` only resolves a single redirect. When using Baïkal behind a proxy with HTTPS, this becomes an issue:

1. dav.example.com/.well-known/caldav (Apache rewrite to http)
2. dav.example.com/dav.php (http)
3. dav.example.com/dav.php (https)

The Apache configuration is provided by Baïkal, hence it is also possible to fix it server-side:

  -RewriteRule /.well-known/carddav /dav.php [R,L]
  +RewriteRule /.well-known/carddav https://dav.example.com/dav.php [R,L]
  -RewriteRule /.well-known/caldav /dav.php [R,L]
  +RewriteRule /.well-known/caldav https://dav.example.com/dav.php [R,L]

This commit follows the well-known URI up to 5 times and returns the (hopefully) correctly resolved url.

### CODE REVIEW

**Comment by posativ** [comment]
Side note: this is probably a side-effect with requests. The request to the not fully resolved URL (http instead of https) causes Baikal to not return a proper principle url. This issue vanished when I changed the `Content-Type: application/xml; charset=UTF-8` to lowercase `Content-Type: application/xml; charset=utf-8` (charset). The redirection of Apache (`mod_rewrite`) uses a latin1 encoding. I didn't investigate further, but something is weird with either my setup or requests.

**Comment by hobarrera** [comment]
Rather than just 5, I'd:

 * Add each url to a list.
 * If the URL is not on the list, continue following redirects.
 * If the URL is on the list, bail (circular redirection).

That's something like:

```python
def find_dav(self):
    uri = self._well_known_uri
    tried_uris = []
    while uri not in tried_uris:
        tried_uris.append(uri)
        # ...
```

**Comment by untitaker** [comment]
This redirect logic would already be in requests itself (`allow_redirects=True`, and reading the `response.url` parameter for the final URL). The reason I did it this way was to spare an unnecessary request at the end, but this request is now necessary to check if another redirect occurs.

On 16 July 2016 22:44:21 CEST, Martin Zimmermann <notifications@github.com> wrote:
>Currently, `find_dav` only resolves a single redirect. When using
>Baïkal behind a proxy with HTTPS, this becomes an issue:
>
>1. dav.example.com/.well-known/caldav (Apache rewrite to http)
>2. dav.example.com/dav.php (http)
>3. dav.example.com/dav.php (https)
>
>The Apache configuration is provided by Baïkal, hence it is also
>possible to fix it server-side:
>
>  -RewriteRule /.well-known/carddav /dav.php [R,L]
>Side note
>+RewriteRule /.well-known/carddav https://dav.example.com/dav.php [R,L]
>  -RewriteRule /.well-known/caldav /dav.php [R,L]
> +RewriteRule /.well-known/caldav https://dav.example.com/dav.php [R,L]
>
>This commit follows the well-known URI up to 5 times and returns the
>(hopefully) correctly resolved url.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/pimutils/vdirsyncer/pull/481
>
>-- Commit Summary --
>
>  * add support for multiple (up to 5) url redirections
>
>-- File Changes --
>
>    M vdirsyncer/storage/dav.py (30)
>
>-- Patch Links --
>
>https://github.com/pimutils/vdirsyncer/pull/481.patch
>https://github.com/pimutils/vdirsyncer/pull/481.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/481

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by posativ** [comment]
So you propose to remove the manual redirection handling and use requests' `allow_redirects=True`?

**Comment by hobarrera** [comment]
I was unaware of `requests` feature. I'd strongly vote to use that instead, yes.

**Comment by untitaker** [comment]
Yup

On 18 July 2016 16:13:04 CEST, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I was unaware of `requests` feature. I'd strongly vote to use that
>instead, yes.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/481#issuecomment-233340291

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Hey @posativ any update on this?

**Comment by posativ** [comment]
Yup, I've rebased the new fix.

**Comment by untitaker** [comment]
Crashes because of https://github.com/PyCQA/flake8-import-order/issues/79. The other build issue with Davical is my fault.

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
