### PR TITLE
Ability to use other collection for missing one

### PR DESCRIPTION
**Pull request by untitaker**
Vdirsyncer asks you if it should create a new collection if the current one is missing, but why not allow using another collection in place?

This idea still needs a lot of UI work. It also shouldn't be possible to "reuse" a collection more than once. Given the amount of complexity a properly polished implementation adds, I'm not sure it's a good idea anyway.

### CODE REVIEW

**Comment by untitaker** [comment]
(cont #416)

@IronWolfMC Check this out, using the second config you tried (the original config with the suggestion from https://github.com/pimutils/vdirsyncer/issues/416#issuecomment-207203700).

**Comment by untitaker** [comment]
Also given that you can just symlink everything together, I am *really* not sure if this change matters.

**Comment by marmarek** [comment]
In case of one backend being a file, you can symlink. But if you for
example sync one caldav with another one (say, google), it isn't
possible (without introducing another complexity of intermediate
storage)..

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by untitaker** [comment]
https://github.com/pimutils/vdirsyncer/pull/423 is the successor.

**Pull request closed without merging**
