### PR TITLE
remove etesync support

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by mathstuf** [comment]
Was there a reason for this?

**Comment by untitaker** [comment]
Nobody was using it

**Comment by mathstuf** [comment]
Ah, I'd like to start using it. I'll patch a version locally though and let you know how it works once I have it deployed.

**Comment by cwegener** [comment]
> Nobody was using it

That sounds a bit ridiculous. Why did the vdirsyncer project initiate contact with the etesync project in the first place then? Sounds like someone wasted some development cycles ...

As an existing user of vdirsyncer, I also am looking at setting up the desktop integration for etesync (which I have recently started using since etesync has a very easy self-hosting option). I'll go back to trying the etesync-dav integration.

**Comment by untitaker** [comment]
@cwegener i can assure you that continued maintenance wastes more time than writing an initial version

**Comment by tasn** [comment]
I just saw this. :scream: :cry: 
For all I know, people were using it, I sent a few people towards vdirsyncer over the years, and chatted to a few pre-existing users. Though I guess that thanks to `etesync-dav` it's not as useful anymore, but still.
What maintenance issues were you facing? Have we changed anything that more difficult for you, or is it more concerning your rewrite/internal changes and having to support more backends?

Note: I'm the maintainer of EteSync. :)

**Comment by untitaker** [comment]
@tasn I think I discussed this with you though beforehand. I was just trying to cut down on things I had to maintain, and remotestorage + etesync storages were candidates.

**Comment by tasn** [comment]
You mentioned you were thinking about dropping it (because of the assumed lack of usage), but I thought you changed your mind after I stated the above. You haven't mentioned the additional maintenance cost. Anyhow, again, just wondering, is it something we did, or just having to support more code?

**Comment by untitaker** [comment]
@tasn No you didn't do anything! Sorry, then I remember this conversation differently. I was sure that I discussed this with you thoroughly. I don't really remember my reasoning at the time, but I think it was because I wanted to remove functionality nobody was using, and thought etesync-dav was the way forward anyway.

**Comment by tasn** [comment]
Cool, just wanted to make sure we didn't inadvertently break anything. :)

etesync-dav is the way forward, but people are using vdirsyncer for all I know. Anyhow, don't worry about it, but this PR caught me by surprise that's all...

**Pull request merged**
