### PR TITLE
CLI worker: Show how many tasks failed

### LINKED ISSUE #398: Show exit status of task
The current sync output looks like this:

    Syncing pair/a
    Syncing pair/b
    Syncing pair/c
    error: a crashed

as described in #397, it's unclear whether `pair/b` and `pair/c` got synchronized.

Proposal:

    Syncing pair/a
    Syncing pair/b
    Syncing pair/c
    error: a crashed
    Syncing pair/a: Failure
    Syncing pair/b: Success
    Syncing pair/c: Success

I'm unsure whether this solves the issue. We might as well just document it in the docs.

This is a successor of #96.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #398

### CODE REVIEW

**Comment by untitaker** [comment]
cc @hobarrera @matthiasbeyer

**Comment by untitaker** [comment]
Screenshot:

2016-04-02-230859_357x94_scrot

**Comment by untitaker** [comment]
@homu r+

**Comment by geier** [comment]
Much better than before

**Pull request merged**
