### PR TITLE
Test development Radicale again

### LINKED ISSUE #410: Development version of Radicale currently fails
Due to an ongoing refactor happening in master (!) of Radicale, the tests for it currently fail.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #410 
- [x] https://github.com/eventable/vobject/pull/23
- [x] https://github.com/Kozea/Radicale/pull/376
- [x] https://github.com/Kozea/Radicale/issues/378
- [x] https://github.com/Kozea/Radicale/pull/380
- [x] https://github.com/Kozea/Radicale/pull/379
- [x] https://github.com/Kozea/Radicale/pull/382
- [x] https://github.com/Kozea/Radicale/issues/384 -- I stopped caring
- [x] https://github.com/Kozea/Radicale/pull/385
- [x] https://github.com/eventable/vobject/issues/18 -- PR at https://github.com/eventable/vobject/pull/33
- [x] https://github.com/Kozea/Radicale/pull/398
- [x] Runtime version check for Radicale
- [x] Wait for release of vobject -- 0.9.3
- [x] https://github.com/Kozea/Radicale/pull/495

### CODE REVIEW

**Comment by untitaker** [comment]
Blocked on https://github.com/eventable/vobject/pull/23

**Comment by untitaker** [comment]
There are two bugs in `vobject` (linked above) that prevent this from getting merged. Unfortunately the developers of vobject are not very responsive. @lize I fear that Radicale 2.0 will reject perfectly valid ICS files because of this.

**Comment by untitaker** [comment]
Argh, latest requests appears to have broken wsgi-intercept.

**Comment by untitaker** [comment]
Essentially caused by https://github.com/requests/requests/issues/4102, fml

**Comment by kennethreitz** [comment]
@untitaker sorry :-/

**Comment by untitaker** [comment]
np

**Pull request merged**
