### PR TITLE
Little spelling fix

### PR DESCRIPTION
**Pull request by amandabee**
Past tense of "occur" is "occurred". 

https://www.wordnik.com/words/occurred

### CODE REVIEW

**Comment by untitaker** [comment]
Hello Amanda, could you run "git grep occured"? I think there is something in the tests folder that still looks for the wrong spelling (which is why the build is red). Thanks!

On 1 January 2018 02:22:10 GMT+01:00, Amanda Hickman <notifications@github.com> wrote:
>Past tense of "occur" is "occurred". 
>
>https://www.wordnik.com/words/occurred
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/pimutils/vdirsyncer/pull/695
>
>-- Commit Summary --
>
>  * Fixed spelling of "occurred"
>  * Fix spelling of occurred.
>
>-- File Changes --
>
>    M tests/unit/test_exceptions.py (2)
>    M vdirsyncer/cli/utils.py (4)
>
>-- Patch Links --
>
>https://github.com/pimutils/vdirsyncer/pull/695.patch
>https://github.com/pimutils/vdirsyncer/pull/695.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/695

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by amandabee** [comment]
@untitaker Fixed it. Looks like it cleared testing this time. Thank you.

**Comment by untitaker** [comment]
Thanks I will hopefully merge tomorrow :)

On 2 January 2018 18:52:09 GMT+01:00, Amanda Hickman <notifications@github.com> wrote:
>@untitaker Fixed it. Looks like it cleared testing this time. Thank
>you. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/695#issuecomment-354829658

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
🎉

**Pull request merged**
