### PR TITLE
Document caveats of Google contacts storage

### PR DESCRIPTION
**Pull request by timoludwig**
Even though it's unclear whether this might be fixed in the future, I guess a note in the docs would be beneficial as long as it isn't.

Thanks in advance for your feedback!

Reference: #814

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Can you also include a link to the upstream issue please? That's https://issuetracker.google.com/issues/36761530

**Comment by timoludwig** [comment]
Alright, done!
I just couldn't find an upstream issue for the BDAY problem, just a few other projects struggling with the same problem:
- https://gitlab.gnome.org/GNOME/evolution/-/issues/1287#note_1100346
- https://gitlab.com/CardBook/CardBook/-/issues/866

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by WhyNotHugo** [comment]
>  I just couldn't find an upstream issue for the BDAY problem, just a few other projects struggling with the same problem:

I'd suggest reporting this upstream, but I don't think Google cares about these bugs, the other bug is 6 years old. And it's the kind of bug where apparently data is simply lost. :shrug:

**Comment by timoludwig** [comment]
Alright, I opened https://issuetracker.google.com/issues/271731853 for this, if I get a response I will update you.

**Pull request merged**
