### PR TITLE
fix google calendar sync

### PR DESCRIPTION
**Pull request by dpaetzel**
Dirty but simple fix for #765. Without this, syncing with Google calendar does not work any more.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Hi! We've rolled back master quite a bit (to the last table release, really).

Do you have issues with v0.16.7? Can you confirm that applying 7b636e8e40d69c495901f965b9c0686513659e44 to is also works for you?

Thanks.

**Comment by dpaetzel** [comment]
Hi! All this PR did was reincluding `prepare_verify` (by copy-paste) which had been removed from the `http` module. It seems that in master, `prepare_verify` is again part of `http`.

However, master throws two kinds of errors for me:
```
cannot import name 'prepare_auth' from 'vdirsyncer.http'
```
and
```
critical: Failed to initialize uni_remote
critical:   - caldav storage doesn't take the parameters: verify_cert, auth_cert_password
```
which make 13 of 25 task fail (although this probably merits opening a new issue).

**Comment by WhyNotHugo** [comment]
Look like your config is set up for the previous master (e.g.: what would have become v0.17).

We've rolled back to 0.16 and work is ongoing based on that, so you'll need to tweak your config file accordingly.

**Comment by dpaetzel** [comment]
After deleting all local files and performing `discover`, the second error no longer occurs :heavy_check_mark: 

However, I still get this:
```
error: Unknown error occurred for google/Me: cannot import name 'prepare_auth' from 'vdirsyncer.http' (/home/david/Code/vdirsyncer/home/lib/python/vdirsyncer-0.16.8.dev68+g68ff37e.d20200614-py3.7.egg/vdirsyncer/http.py)
```
which doesn't seem config-related to me?

**Pull request closed without merging**
