### PR TITLE
Fix OSX

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by untitaker** [comment]
Right now the tests **on master** are failing on OS X. I didn't manage to install Hackintosh to test this :(

**Comment by hobarrera** [comment]
I've an OSX VM on my laptop; *If* it works on my desktop, I'll give you SSH access to it (I don't actually use it).

No guarantees, though, since OSX isn't supposed to work on my desktop processor (AMD FX).

**Comment by untitaker** [comment]
That would be great. How did you get it to run and which virtualization software are you using on which host OS?

On 30 March 2017 00:25:16 CEST, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I've an OSX VM on my laptop; *If* it works on my desktop, I'll give you
>SSH access to it (I don't actually use it).
>
>No guarantees, though, since OSX isn't supposed to work on my desktop
>processor (AMD FX).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/612#issuecomment-290245154

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
VirtualBox on ArchLinux. It's official supported. I did have to jump through hoops to generate the installation ISO (basically had to generate is using OSX and some online scripts.).

**Comment by untitaker** [comment]
See #618

**Pull request closed without merging**
