### PR TITLE
Use MKCALENDAR

### LINKED ISSUE #570: Investigate switch from MKCOL to MKCALENDAR for caldav.
When synchronizing calendars with iCloud using the `caldav` storage, created collections don't support VTODO entries. As outlined in https://github.com/pimutils/vdirsyncer/pull/567#issuecomment-283036234 this may be fixed by using MKCALENDAR instead of MKCOL to create calendars.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #570

### CODE REVIEW

**Comment by hobarrera** [comment]
I'd also include a test uploading a vcard to iCloud on this PR to confirm that this has the desired effect (I suspect it does).

**Comment by untitaker** [comment]
For now I'm just trying to get the CI to pass

**Comment by untitaker** [comment]
iCloud only lets us create a collection that is *either* a calendar *or* a tasklist. See https://travis-ci.org/pimutils/vdirsyncer/jobs/210239842#L782:

    debug: <html><head><title>Bad Request</title></head><body><h1>Bad Request</h1><p>Calendar SupportedCalendarComponentSet length exceeded, only one calendar component type supported</p></body></html>

Vdirsyncer could support an additional storage param that decides what to create, but I think it's just way easier if users created collections in the web interface.

**Comment by hobarrera** [comment]
Wow, that's really bad UX (on iCloud's side), since the iOS app lets me create both VTODOs and VEVENTs on the same calendar. I wonder how they deal with that when syncing with iCloud. :/

**Pull request closed without merging**
