### PR TITLE
Enable PyPy3

### LINKED ISSUE #429: Test against pypy Python 3 in CI
I want vdirsyncer to be able to run on some version of Pypy. If we're going to kill support for Python 2, we should activate the pypy3 Python version in Travis.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #429

### CODE REVIEW

**Comment by hobarrera** [comment]
Since I'd like to imitate this for todoman, I'd like to understand this further; you're ignoring the travis-provided pypy, and installing it manually via `pyenv`, correct?

I take it the travis-provided one didn't work?

**Comment by untitaker** [comment]
The Travis-provided one was too old, I think it targeted Python 3.2. Theoretically we could make vdirsyncer 3.2-compatible now that we don't support Python 2 anymore (we relied on usage of `u""`-strings, which are only available in Py2 and Py3.3+), but I don't have the incentive to do that.

**Comment by untitaker** [comment]
Also yes we're installing a newer pypy3 into `$HOME` (not system-wide), but without removing the old one from travis.

**Comment by hobarrera** [comment]
Hmm. Thanks. todoman's travis setup is a lot simpler and I'd rather wait for travis to update and not make it more complex.

**Pull request merged**
