### PR TITLE
Add a --config-file option.

### PR DESCRIPTION
**Pull request by lucc**

### CODE REVIEW

**Comment by untitaker** [comment]
Implementation looks solid and I've been meaning to add this myself. I'd like to have it named --config though, what do you think?

On 7 April 2016 12:17:32 CEST, Lucas Hoffmann <notifications@github.com> wrote:
>
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/pimutils/vdirsyncer/pull/409
>
>-- Commit Summary --
>
>  * Add a --config-file option.
>
>-- File Changes --
>
>    M vdirsyncer/cli/__init__.py (6)
>    M vdirsyncer/cli/config.py (7)
>
>-- Patch Links --
>
>https://github.com/pimutils/vdirsyncer/pull/409.patch
>https://github.com/pimutils/vdirsyncer/pull/409.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/pull/409

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lucc** [comment]
Fine with me, will amend it.

**Comment by geier** [comment]
Quoting Markus Unterwaditzer (2016-04-07 15:34:39)
> Implementation looks solid and I've been meaning to add this myself. I'd like to have it named --config though, what do you think?

agree.

**Comment by untitaker** [comment]
Sorry I forgot, could you add a changelog as well? Including a PR reference like in previous entries. Thanks!

**Comment by lucc** [comment]
done

**Comment by untitaker** [comment]
@homu r+

**Comment by untitaker** [comment]
Bleh, see #410.

@homu retry

**Pull request merged**
